### ISSUE TITLE
Ja foi testado em alguma LOja Virtual em produção?

### ISSUE THREAD

**Issue by leandrobosaipo** [kasterweb/kasterweb-magento-cleaner#1]

**Comment by dhyegocalota** [comment]
It has been done in eletricaparana.com.br
Is that something else which I can help you with?

Thanks,
best regards.

**Comment by dhyegocalota** [comment]
Please pay attention:

I can't speak portuguese very well and google translator has some kind of issues with that. Could you write in english next time? Thank you.

**Comment by leandrobosaipo** [comment]
xiken
